# Use a imagem base oficial do Golang
FROM golang:1.22.2-alpine

# Crie e defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo go.mod e go.sum para o diretório de trabalho
COPY go.mod go.sum ./

# Baixe as dependências
RUN go mod download

# Copie o código fonte para o contêiner
COPY . .

# Compile o aplicativo
RUN go build -o main .

# Exponha a porta em que a aplicação irá rodar
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["./main"]
